### ISSUE TITLE
README: Readme & Deploy

### ISSUE THREAD

**Issue by knpausch** [knpausch/my-comic-book-guy-reviews#11]
- [x] Deploy site (Vercel)
- [x] README concisely communicates your learning goals, the evolution of the project, and reflections while using good formatting to enhance readability
- [x] README links to any applicable repos/deployed sites and includes clear instructions for running the application locally
- [x] README includes the deployed link and it is easy to locate
- [x] README includes a gif of the application
- [x] README includes future extensions: 
- Revote after voting on a episode
- Show season and episode num on thumbnails
- If user enters in URL, have it refetch data
- Filter home view by episode name

**Comment by patel-aum** [comment]
I can deployed it but it will be from my forked repo

**Comment by patel-aum** [comment]
https://my-comic-book.vercel.app/   

> I can deployed it but it will be from my forked repo
